// Official 2026 Formula 1 calendar: 23 Grands Prix.
//
// `length`, `laps` and `date` are the real published figures. Everything else
// is invented for the demo, but invented consistently:
//
//   lapBase  fictional representative race lap in seconds, scaled from Spa's
//            real ~1:47.2 to suit each circuit. Drives the lap clock, the car
//            motion speed and the sector splits.
//   sectors  real named features of each layout, so the copy follows the map.
//   corner   the circuit's signature corner, used in the hero headline and the
//            race control incident.
//   weather  fictional conditions, plausible for that venue in that month.
//            Not a live feed: this project has no dependencies and no network
//            calls of its own beyond the optional track diagrams.
const OFFICIAL_F1_CIRCUITS = [
  { slug: 'australia', country: 'Australia', name: 'Australia · Melbourne', length: '5.278km', laps: 58, date: 'Sunday, 8 March', venue: 'Melbourne', lapBase: 80.1, sectors: ['Turn 1 → Turn 6', 'Turn 6 → Turn 11', 'Turn 11 → Bus Stop'], corner: 'Turn 1', weather: { air: 21, track: 31, rain: 20, wind: 'SE 15 km/h', asphalt: 'WARM · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/australia', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackmelbournedetailed.webp' },
  { slug: 'china', country: 'China', name: 'China · Shanghai', length: '5.451km', laps: 56, date: 'Sunday, 15 March', venue: 'Shanghai', lapBase: 94.0, sectors: ['Turn 1 → Turn 9', 'Turn 9 → Turn 13', 'Turn 13 → Bus Stop'], corner: 'Turn 11', weather: { air: 14, track: 24, rain: 45, wind: 'E 10 km/h', asphalt: 'COOL · DAMP' }, eventUrl: 'https://www.formula1.com/en/racing/2026/china', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackshanghaidetailed.webp' },
  { slug: 'japan', country: 'Japan', name: 'Japan · Suzuka', length: '5.807km', laps: 53, date: 'Sunday, 29 March', venue: 'Suzuka', lapBase: 91.3, sectors: ['Turn 1 → S Curves', 'S Curves → Degner', 'Degner → Bus Stop'], corner: 'the S Curves', weather: { air: 13, track: 22, rain: 40, wind: 'W 8 km/h', asphalt: 'COOL · COOLING' }, eventUrl: 'https://www.formula1.com/en/racing/2026/japan', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026tracksuzukadetailed.webp' },
  { slug: 'miami', country: 'United States', name: 'Miami · Miami International Autodrome', length: '5.412km', laps: 57, date: 'Sunday, 3 May', venue: 'Miami', lapBase: 89.8, sectors: ['Turn 1 → Turn 11', 'Turn 11 → Turn 17', 'Turn 17 → Bus Stop'], corner: 'Turn 17', weather: { air: 29, track: 38, rain: 50, wind: 'E 12 km/h', asphalt: 'HOT · HUMID' }, eventUrl: 'https://www.formula1.com/en/racing/2026/miami', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackmiamidetailed.webp' },
  { slug: 'canada', country: 'Canada', name: 'Canada · Montreal', length: '4.361km', laps: 70, date: 'Sunday, 24 May', venue: 'Montreal', lapBase: 73.9, sectors: ['Turn 1 → Turn 8', 'Turn 8 → Turn 14', 'Turn 14 → Bus Stop'], corner: 'the Wall of Champions', weather: { air: 17, track: 27, rain: 35, wind: 'SW 14 km/h', asphalt: 'WARM · COOLING' }, eventUrl: 'https://www.formula1.com/en/racing/2026/canada', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackmontrealdetailed.webp' },
  { slug: 'monaco', country: 'Monaco', name: 'Monaco · Monte Carlo', length: '3.337km', laps: 78, date: 'Sunday, 7 June', venue: 'Monte Carlo', lapBase: 73.0, sectors: ['Hairpin → Massenet', 'Massenet → Casino', 'Casino → Bus Stop'], corner: 'Massenet', weather: { air: 24, track: 34, rain: 15, wind: 'E 9 km/h', asphalt: 'WARM · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/monaco', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackmontecarlodetailed.webp' },
  { slug: 'barcelona-catalunya', country: 'Spain', name: 'Spain · Barcelona-Catalunya', length: '4.657km', laps: 66, date: 'Sunday, 14 June', venue: 'Catalunya', lapBase: 78.6, sectors: ['Turn 1 → Turn 4', 'Turn 4 → Turn 10', 'Turn 10 → Bus Stop'], corner: 'Campsa', weather: { air: 28, track: 42, rain: 10, wind: 'S 8 km/h', asphalt: 'HOT · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/barcelona-catalunya', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackcatalunyadetailed.webp' },
  { slug: 'austria', country: 'Austria', name: 'Austria · Spielberg', length: '4.326km', laps: 71, date: 'Sunday, 28 June', venue: 'Spielberg', lapBase: 76.2, sectors: ['Turn 1 → Turn 3', 'Turn 3 → Turns 6-7', 'Turns 6-7 → Bus Stop'], corner: 'Turn 3', weather: { air: 21, track: 35, rain: 45, wind: 'N 10 km/h', asphalt: 'WARM · DAMP' }, eventUrl: 'https://www.formula1.com/en/racing/2026/austria', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackspielbergdetailed.webp' },
  { slug: 'great-britain', country: 'Great Britain', name: 'Great Britain · Silverstone', length: '5.891km', laps: 52, date: 'Sunday, 5 July', venue: 'Silverstone', lapBase: 88.9, sectors: ['Abbey → Copse', 'Copse → Stowe', 'Stowe → Bus Stop'], corner: 'Copse', weather: { air: 18, track: 28, rain: 40, wind: 'SW 16 km/h', asphalt: 'COOL · DAMP' }, eventUrl: 'https://www.formula1.com/en/racing/2026/great-britain', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026tracksilverstonedetailed.webp' },
  { slug: 'belgium', country: 'Belgium', name: 'Belgium · Spa-Francorchamps', length: '7.004km', laps: 44, date: 'Sunday, 19 July', venue: 'Spa', lapBase: 107.228, sectors: ['La Source → Raidillon', 'Les Combes → Fagnes', 'Stavelot → Bus Stop'], corner: 'Eau Rouge', weather: { air: 18, track: 26, rain: 30, wind: 'NW 8 km/h', asphalt: 'DRY · COOLING' }, eventUrl: 'https://www.formula1.com/en/racing/2026/belgium', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackspafrancorchampsdetailed.webp' },
  { slug: 'hungary', country: 'Hungary', name: 'Hungary · Hungaroring', length: '4.381km', laps: 70, date: 'Sunday, 26 July', venue: 'Hungaroring', lapBase: 78.2, sectors: ['Turn 1 → Turn 4', 'Turn 4 → Turn 11', 'Turn 11 → Bus Stop'], corner: 'Turn 2', weather: { air: 27, track: 41, rain: 20, wind: 'NE 9 km/h', asphalt: 'HOT · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/hungary', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackhungaroringdetailed.webp' },
  { slug: 'netherlands', country: 'Netherlands', name: 'Netherlands · Zandvoort', length: '4.259km', laps: 72, date: 'Sunday, 23 August', venue: 'Zandvoort', lapBase: 72.5, sectors: ['Tarzan → Gerlach', 'Gerlach → Hugenholtz', 'Hugenholtz → Bus Stop'], corner: 'Gerlach', weather: { air: 20, track: 30, rain: 35, wind: 'W 13 km/h', asphalt: 'WARM · COOLING' }, eventUrl: 'https://www.formula1.com/en/racing/2026/netherlands', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackzandvoortdetailed.webp' },
  { slug: 'italy', country: 'Italy', name: 'Italy · Monza', length: '5.793km', laps: 53, date: 'Sunday, 6 September', venue: 'Monza', lapBase: 81.3, sectors: ['Rettifilo → Variante', 'Variante → Lesmo 2', 'Lesmo 2 → Bus Stop'], corner: 'Variante della Roggia', weather: { air: 24, track: 36, rain: 15, wind: 'N 7 km/h', asphalt: 'WARM · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/italy', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackmonzadetailed.webp' },
  // Two Spanish rounds in 2026 and they are easy to confuse. The Spanish Grand
  // Prix is the new one in Madrid; the old Spanish race at Montmelo keeps a
  // race of its own under the name Barcelona-Catalunya Grand Prix.
  { slug: 'spain', country: 'Spain', name: 'Spain · Madring (Madrid)', length: '5.414km', laps: 57, date: 'Sunday, 13 September', venue: 'MADRING', lapBase: 94.6, sectors: ['Turn 1 → Turn 8', 'Turn 8 → Turn 15', 'Turn 15 → Bus Stop'], corner: 'Turn 8', weather: { air: 29, track: 41, rain: 5, wind: 'SW 6 km/h', asphalt: 'HOT · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/spain', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackmadringdetailed.webp' },
  // The 2026 Azerbaijan race moved to a Saturday at the promoter's request,
  // to sit alongside the country's Remembrance Day. It is the one round that is
  // not a Sunday, so the desk's "Sunday race" framing does not apply here.
  { slug: 'azerbaijan', country: 'Azerbaijan', name: 'Azerbaijan · Baku', length: '6.003km', laps: 51, date: 'Saturday, 26 September', venue: 'Baku', lapBase: 101.4, sectors: ['Turn 1 → Turn 3', 'Turn 3 → Turn 15', 'Turn 15 → Bus Stop'], corner: 'Turn 15', weather: { air: 27, track: 40, rain: 5, wind: 'N 12 km/h', asphalt: 'HOT · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/azerbaijan', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackbakudetailed.webp' },
  // The 2026 Bahrain Grand Prix is being run at Sepang, Malaysia: the April
  // race at Sakhir was cancelled, and Malaysia agreed to host it in October.
  // So the slug says "bahrain" but the venue, length, lap count and map are
  // all Sepang. Sakhir does not appear on the 2026 calendar, and there is no
  // Saudi Arabian round either — Jeddah was cancelled and not replaced.
  { slug: 'bahrain', country: 'Malaysia', name: 'Bahrain GP · Sepang, Malaysia', length: '5.543km', laps: 56, date: 'Sunday, 4 October', venue: 'Sepang', lapBase: 94.1, sectors: ['Turn 1 → Turn 7', 'Turn 7 → Turn 13', 'Turn 13 → Bus Stop'], corner: 'the Langkawi Curve', weather: { air: 32, track: 44, rain: 45, wind: 'SW 5 km/h', asphalt: 'HOT · HUMID' }, eventUrl: 'https://www.formula1.com/en/racing/2026/bahrain', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackkualalumpurdetailed.webp' },
  { slug: 'singapore', country: 'Singapore', name: 'Singapore · Marina Bay', length: '4.927km', laps: 62, date: 'Sunday, 11 October', venue: 'Marina Bay', lapBase: 89.0, sectors: ['Turn 1 → Turn 8', 'Turn 8 → Turns 13-14', 'Turns 13-14 → Bus Stop'], corner: 'Turn 8', weather: { air: 29, track: 36, rain: 55, wind: 'SE 8 km/h', asphalt: 'HOT · HUMID' }, eventUrl: 'https://www.formula1.com/en/racing/2026/singapore', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026tracksingaporedetailed.webp' },
  { slug: 'united-states', country: 'United States', name: 'United States · Austin', length: '5.513km', laps: 56, date: 'Sunday, 25 October', venue: 'Austin', lapBase: 96.2, sectors: ['Turn 1 → Turn 11', 'Turn 11 → Turn 16', 'Turn 16 → Bus Stop'], corner: 'Turn 11', weather: { air: 26, track: 38, rain: 15, wind: 'N 8 km/h', asphalt: 'WARM · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/united-states', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackaustindetailed.webp' },
  { slug: 'mexico', country: 'Mexico', name: 'Mexico City · Autódromo Hermanos Rodríguez', length: '4.304km', laps: 71, date: 'Sunday, 1 November', venue: 'Mexico City', lapBase: 76.8, sectors: ['Turn 1 → Turn 4', 'Turn 4 → Foro Sol', 'Foro Sol → Bus Stop'], corner: 'Foro Sol', weather: { air: 22, track: 32, rain: 20, wind: 'N 9 km/h', asphalt: 'WARM · COOLING' }, eventUrl: 'https://www.formula1.com/en/racing/2026/mexico', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackmexicocitydetailed.webp' },
  { slug: 'brazil', country: 'Brazil', name: 'Brazil · Interlagos', length: '4.309km', laps: 71, date: 'Sunday, 8 November', venue: 'Interlagos', lapBase: 71.4, sectors: ['Turn 1 → Laranja', 'Laranja → Pinheirinhos', 'Pinheirinhos → Bus Stop'], corner: 'Ferradura', weather: { air: 24, track: 33, rain: 50, wind: 'SE 11 km/h', asphalt: 'WARM · DAMP' }, eventUrl: 'https://www.formula1.com/en/racing/2026/brazil', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackinterlagosdetailed.webp' },
  // Provisional: the late-season rounds are still subject to the FIA's
  // decision on the Qatar and Abu Dhabi dates.
  { slug: 'las-vegas', country: 'United States', name: 'Las Vegas · Strip Circuit', length: '6.201km', laps: 50, date: 'Saturday, 21 November', venue: 'Las Vegas', lapBase: 95.0, sectors: ['Turn 1 → Turn 5', 'Turn 5 → Long Straight', 'Long Straight → Bus Stop'], corner: 'Turn 5', weather: { air: 18, track: 30, rain: 5, wind: 'NW 7 km/h', asphalt: 'WARM · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/las-vegas', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026tracklasvegasdetailed.webp' },
  { slug: 'qatar', country: 'Qatar', name: 'Qatar · Lusail', length: '5.419km', laps: 57, date: 'Sunday, 29 November', venue: 'Lusail', lapBase: 91.5, sectors: ['Turn 1 → Turn 10', 'Turn 10 → Turn 16', 'Turn 16 → Bus Stop'], corner: 'Turn 10', weather: { air: 28, track: 40, rain: 3, wind: 'N 13 km/h', asphalt: 'HOT · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/qatar', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026tracklusaildetailed.webp' },
  { slug: 'united-arab-emirates', country: 'United Arab Emirates', name: 'Abu Dhabi · Yas Marina', length: '5.281km', laps: 58, date: 'Sunday, 6 December', venue: 'Yas Marina', lapBase: 85.0, sectors: ['Turn 1 → Turn 5', 'Turn 5 → Turn 13', 'Turn 13 → Bus Stop'], corner: 'Turn 5', weather: { air: 27, track: 36, rain: 5, wind: 'NW 11 km/h', asphalt: 'WARM · DRY' }, eventUrl: 'https://www.formula1.com/en/racing/2026/united-arab-emirates', mapUrl: 'https://media.formula1.com/image/upload/c_fit,h_704/q_auto/v1740000001/common/f1/2026/track/2026trackyasmarinacircuitdetailed.webp' },
];
